apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-d0kz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-d0kz
    app.kubernetes.io/part-of: e2e-springboot
  name: devfile-sample-java-springboot-basic-d0kz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-d0kz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-d0kz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mkgv-tenant/e2e-springboot/devfile-sample-java-springboot-basic-d0kz@sha256:1942e43b19c5907f7210cfeefdcb69145b2d3c41aa74cc41cb13064a55cfd6ef
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
